import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  const token = process.env.TOKEN_IXC;
  const url = process.env.URL_IXC;

  const dataExpiracao = new Date();
  dataExpiracao.setDate(dataExpiracao.getDate() + 365);
  const dia = dataExpiracao.getDate().toString().padStart(2, '0');
  const mes = (dataExpiracao.getMonth() + 1).toString().padStart(2, '0');
  const ano = dataExpiracao.getFullYear().toString();
  const dataExpiracaoFormatada = `${dia}/${mes}/${ano}`;

  

  const {
    id_cliente,
    id_vd_contrato,
    dia_vencimento,
    id_carteira_cobranca,
    id_descricao_plano,
    id_tipo_doc,
    tipo_doc_opc,
    id_modelo,
    bairro,
    cep,
    idCidade,
    idFilial,
    complemento,
    logradouro,
    numero,
  } = await request.json();

  const options = {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: "Basic " + Buffer.from(token ?? "").toString("base64"),
    },
    body: JSON.stringify({
      tipo: "I",
      id_cliente: id_cliente,
      id_vd_contrato: id_vd_contrato,
      descricao_aux_plano_venda: id_descricao_plano,
      contrato: id_descricao_plano,
      id_tipo_contrato: dia_vencimento,
      id_modelo: id_modelo,
      assinatura_digital: "P",
      integracao_assinatura_digital: "P",
      liberacao_bloqueio_manual: "P",
      id_filial: idFilial,
      indicacao_contrato_id: "",
      data_assinatura: "",
      data_ativacao: "",
      data: "CURRENT_TIMESTAMP",
      data_renovacao: "",
      pago_ate_data: "",
      status: "P",
      status_internet: "AA",
      status_velocidade: "N",
      tipo_produtos_plano: "P",
      motivo_inclusao: "I",
      id_indexador_reajuste: "",
      url_assinatura_digital: "",
      token_assinatura_digital: "",
      id_tipo_documento: id_tipo_doc,
      id_carteira_cobranca: id_carteira_cobranca,
      id_vendedor: "121",
      moeda: "",
      comissao: "",
      cc_previsao: "P",
      tipo_cobranca: "P",
      renovacao_automatica: "S",
      gerar_finan_assin_digital_contrato: "P",
      base_geracao_tipo_doc: "P",
      id_contrato_principal: "",
      num_parcelas_atraso: "",
      nf_info_adicionais: "",
      credit_card_recorrente_bandeira_cartao: "",
      credit_card_recorrente_token: "",
      ids_contratos_recorrencia: "",
      tipo_doc_opc: tipo_doc_opc,
      tipo_doc_opc2: "",
      tipo_doc_opc3: "",
      tipo_doc_opc4: "",
      id_tipo_doc_ativ: "",
      id_produto_ativ: "",
      taxa_instalacao: "0.00",
      id_cond_pag_ativ: "",
      id_responsavel: "",
      id_vendedor_ativ: "",
      ativacao_numero_parcelas: "",
      ativacao_vencimentos: "",
      btn_nf_ativacao: "",
      ativacao_valor_parcela: "",
      fidelidade: "12",
      data_expiracao: dataExpiracaoFormatada,
      dica_data_expiracao: "",
      desconto_fidelidade: "0.00",
      id_instalador: "",
      taxa_improdutiva: "",
      venc_personalizado: "",
      com_entrada: "",
      dia_fixo_vencimento: "",
      tipo_condicao_pag: "",
      bloqueio_automatico: "S",
      nao_bloquear_ate: "",
      aviso_atraso: "S",
      nao_avisar_ate: "",
      desbloqueio_confianca: "P",
      desbloqueio_confianca_ativo: "N",
      restricao_auto_desbloqueio: "N",
      motivo_restricao_auto_desbloq: "",
      obs: "",
      nao_susp_parc_ate: "",
      liberacao_suspensao_parcial: "P",
      utilizando_auto_libera_susp_parc: "N",
      restricao_auto_libera_susp_parcial: "N",
      motivo_restri_auto_libera_parc: "",
      contrato_suspenso: "N",
      data_inicial_suspensao: "",
      data_final_suspensao: "",
      data_acesso_desativado: "",
      data_cancelamento: "",
      id_responsavel_cancelamento: "",
      motivo_cancelamento: "",
      motivo_adicional: "",
      concorrente_mot_adicional: "",
      dica_motivo_adicional_cliente_contrato: "",
      obs_cancelamento: "",
      data_negativacao: "",
      id_responsavel_negativacao: "",
      protocolo_negativacao: "",
      id_motivo_negativacao: "",
      obs_negativacao: "",
      data_desistencia: "",
      id_responsavel_desistencia: "",
      motivo_desistencia: "",
      obs_desistencia: "",
      obs_contrato: "",
      alerta_contrato: "",
      imp_realizado: "S",
      imp_inicial: "",
      imp_carteira: "N",
      imp_importacao: "N",
      imp_treinamento: "N",
      imp_rede: "N",
      imp_bkp: "N",
      imp_obs: "",
      imp_final: "",
      imp_status: "A",
      imp_motivo: "",
      dt_ult_bloq_auto: "",
      dt_ult_bloq_manual: "",
      dt_ult_finan_atraso: "",
      dt_ult_des_bloq_conf: "",
      dt_ult_liberacao_susp_parc: "",
      dt_ult_ativacao: "",
      dt_utl_negativacao: "",
      dt_ult_desiste: "",
      data_cadastro_sistema: "",
      ultima_atualizacao: "CURRENT_TIMESTAMP",
      data_retomada_contrato: "NULL",
      endereco_padrao_cliente: "N",
      endereco_padrao_alert: "",
      id_condominio: "",
      condominio_novo: "",
      bloco: "",
      bloco_novo: "",
      apartamento: "",
      apartamento_novo: "",
      cep: cep,
      cep_novo: "",
      endereco: logradouro,
      endereco_novo: "",
      numero: numero,
      numero_novo: "",
      bairro: bairro,
      bairro_novo: "",
      cidade: idCidade,
      cidade_novo: "",
      complemento: complemento,
      complemento_novo: "",
      referencia: "",
      referencia_novo: "",
      latitude: "",
      latitude_novo: "",
      longitude: "",
      longitude_novo: "",
      avalista_1: "",
      avalista_2: "",
      testemunha_assinatura_digital: "",
      document_photo: "P",
      selfie_photo: "P",
    }),
  };

  const response = await fetch(`${url}/cliente_contrato`, options);

  const data = await response.json();

  return NextResponse.json(data);
}
