import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  const token = process.env.TOKEN_IXC;
  const url = process.env.URL_IXC;

  const {
    cpfCnpj,
    nomeCompleto,
    telefone,
    email,
    rg,
    dataNascimento,
    bairro,
    cep,
    idCidade,
    idFilial,
    complemento,
    logradouro,
    numero,
  } = await request.json();

  const nomeMaiusculo = nomeCompleto.toUpperCase();
  const dataNascimentoObj = new Date(dataNascimento);
  const dia = dataNascimentoObj.getDate().toString().padStart(2, "0");
  const mes = (dataNascimentoObj.getMonth() + 1).toString().padStart(2, "0");
  const ano = dataNascimentoObj.getFullYear().toString();
  const dataNascimentoFormatada = `${dia}/${mes}/${ano}`;

  const options = {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: "Basic " + Buffer.from(token ?? "").toString("base64"),
    },
    body: JSON.stringify({
      ativo: "S",
      id_tipo_cliente: "",
      tipo_cliente_scm: "01",
      tipo_pessoa: "F",
      razao: nomeMaiusculo,
      fantasia: "",
      cnpj_cpf: cpfCnpj,
      ie_identidade: rg,
      contribuinte_icms: "N",
      rg_orgao_emissor: "",
      nacionalidade: "Brasileiro",
      cidade_naturalidade: "",
      estado_nascimento: "",
      data_nascimento: dataNascimentoFormatada,
      Sexo: "",
      profissao: "",
      estado_civil: "",
      inscricao_municipal: "",
      isuf: "",
      tipo_assinante: "3",
      filial_id: idFilial,
      filtra_filial: "S",
      idx: "",
      data_cadastro: "CURRENT_TIMESTAMP",
      ativo_serasa: "",
      convert_cliente_forn: "N",
      atualizar_cadastro_galaxPay: "N",
      grau_satisfacao: "",
      id_condominio: "",
      bloco: "",
      apartamento: "",
      cep: cep,
      cif: "",
      endereco: logradouro,
      numero: numero,
      complemento: complemento ?? "",
      bairro: bairro,
      cidade: idCidade,
      referencia: "",
      uf: "1",
      moradia: "",
      tipo_localidade: "U",
      latitude: "",
      longitude: "",
      cep_cob: "",
      endereco_cob: "",
      numero_cob: "",
      bairro_cob: "",
      cidade_cob: "",
      complemento_cob: "",
      referencia_cob: "",
      uf_cob: "",
      fone: "",
      telefone_comercial: "",
      ramal: "",
      id_operadora_celular: "",
      telefone_celular: telefone,
      whatsapp: telefone,
      email: email,
      email_opa: "",
      contato: "",
      website: "",
      skype: "",
      facebook: "",
      hotsite_email: email,
      senha: email,
      acesso_automatico_central: "P",
      alterar_senha_primeiro_acesso: "P",
      senha_hotsite_md5: "N",
      hotsite_acesso: "2",
      crm: "N",
      id_candato_tipo: "16",
      id_campanha: "",
      id_concorrente: "",
      id_perfil: "",
      responsavel: "",
      indicado_por: "",
      cadastrado_via_viabilidade: "N",
      status_prospeccao: "C",
      crm_data_novo: "",
      crm_data_sondagem: "",
      crm_data_apresentando: "",
      crm_data_negociando: "",
      crm_data_vencemos: "",
      crm_data_perdemos: "",
      crm_data_abortamos: "",
      crm_data_sem_porta_disponivel: "",
      crm_data_sem_viabilidade: "",
      pipe_id_organizacao: "",
      foto_cartao: "",
      participa_cobranca: "S",
      num_dias_cob: "",
      participa_pre_cobranca: "S",
      cob_envia_email: "S",
      cob_envia_sms: "S",
      id_conta: "",
      cond_pagamento: "",
      id_vendedor: "121",
      tabela_preco: "",
      deb_automatico: "",
      deb_agencia: "",
      deb_conta: "",
      codigo_operacao: "",
      tipo_pessoa_titular_conta: "F",
      cnpj_cpf_titular_conta: "",
      ultima_atualizacao: "CURRENT_TIMESTAMP",
      nome_pai: "",
      cpf_pai: "",
      identidade_pai: "",
      nascimento_pai: "",
      nome_mae: "",
      cpf_mae: "",
      identidade_mae: "",
      nascimento_mae: "",
      quantidade_dependentes: "",
      nome_conjuge: "",
      fone_conjuge: "",
      cpf_conjuge: "",
      rg_conjuge: "",
      data_nascimento_conjuge: "",
      nome_contador: "",
      telefone_contador: "",
      orgao_publico: "N",
      im: "",
      nome_representante_1: "",
      cpf_representante_1: "",
      identidade_representante_1: "",
      nome_representante_2: "",
      cpf_representante_2: "",
      identidade_representante_2: "",
      emp_empresa: "",
      emp_cnpj: "",
      emp_cep: "",
      emp_endereco: "",
      emp_cidade: "",
      emp_fone: "",
      emp_cargo: "",
      emp_remuneracao: "",
      emp_data_admissao: "",
      iss_classificacao_padrao: "99",
      pis_retem: "N",
      cofins_retem: "N",
      csll_retem: "N",
      irrf_retem: "N",
      desconto_irrf_valor_inferior: "S",
      cli_desconta_iss_retido_total: "N",
      dica_imposto_retido_cliente: "",
      ref_com_empresa1: "",
      ref_com_fone1: "",
      ref_com_empresa2: "",
      ref_com_fone2: "",
      ref_pes_nome1: "",
      ref_pes_fone1: "",
      ref_pes_nome2: "",
      ref_pes_fone2: "",
      obs: "",
      alerta: "",
    }),
  };

  const response = await fetch(`${url}/cliente`, options);

  const data = await response.json();

  return NextResponse.json(data);
}
