export interface IContratosResponse {
  page: string;
  total: string;
  registros: IContratos[];
}
export type TStatus = "P" | "A" | "I" | "N" | "D";
export type TStatusInternet = "A" | "D" | "CM" | "CA" | "FA" | "AA" | "I";
export type TBloqueioAutomatico = "S" | "N";
export type TAvisoAtraso = "S" | "N";
export type TDesbloqueioConfianca = "P" | "N";
export type TTipoCobranca = "P" | "N";
export type TRenovacaoAutomatica = "S" | "N";
export type TContratoSuspenso = "S" | "N";
export type TEnderecoPadraoCliente = "S" | "N";
export type TAssinaturaDigital = "P" | "N";
export type TBaseGeracaoTipoDoc = "P" | "N";

export interface IContratos {
  id_instalador: string;
  indicacao_contrato_id: string;
  id_indexador_reajuste: string;
  data_desistencia: string;
  motivo_desistencia: string;
  obs_desistencia: string;
  obs_contrato: string;
  alerta_contrato: string;
  ids_contratos_recorrencia: string;
  id_responsavel_desistencia: string;
  id_responsavel_cancelamento: string;
  id_responsavel_negativacao: string;
  id: string;
  id_filial: string;
  status: TStatus;
  status_internet: TStatusInternet;
  id_cliente: string;
  data_assinatura: string;
  data_ativacao: string;
  data: string;
  data_renovacao: string;
  bloqueio_automatico: TBloqueioAutomatico;
  imp_carteira: string;
  data_expiracao: string;
  pago_ate_data: string;
  id_vd_contrato: string;
  contrato: string;
  endereco: string;
  numero: string;
  valor: string;
  bairro: string;
  comissao: string;
  tipo: string;
  descricao_aux_plano_venda: string;
  id_tipo_contrato: string;
  aviso_atraso: TAvisoAtraso;
  id_carteira_cobranca: string;
  obs: string;
  status_velocidade: string;
  id_vendedor: string;
  id_modelo: string;
  nao_avisar_ate: string;
  cc_previsao: string;
  nao_bloquear_ate: string;
  id_tipo_documento: string;
  tipo_doc_opc: string;
  tipo_doc_opc2: string;
  desconto_fidelidade: string;
  tipo_doc_opc3: string;
  tipo_doc_opc4: string;
  taxa_improdutiva: string;
  desbloqueio_confianca: TDesbloqueioConfianca;
  data_negativacao: string;
  data_acesso_desativado: string;
  motivo_cancelamento: string;
  data_cancelamento: string;
  obs_cancelamento: string;
  id_vendedor_ativ: string;
  fidelidade: string;
  tipo_cobranca: TTipoCobranca;
  desbloqueio_confianca_ativo: string;
  id_responsavel: string;
  taxa_instalacao: string;
  dt_ult_bloq_auto: string;
  protocolo_negativacao: string;
  dt_ult_bloq_manual: string;
  dt_ult_des_bloq_conf: string;
  dt_ult_ativacao: string;
  dt_ult_finan_atraso: string;
  avalista_1: string | "";
  dt_utl_negativacao: string;
  avalista_2: string | "";
  data_cadastro_sistema: string;
  ultima_atualizacao: string;
  complemento: string;
  cidade: string;
  imp_importacao: string;
  renovacao_automatica: TRenovacaoAutomatica;
  imp_rede: string;
  motivo_inclusao: string;
  imp_bkp: string;
  liberacao_bloqueio_manual: string;
  imp_treinamento: string;
  contrato_suspenso: TContratoSuspenso;
  imp_status: string;
  imp_obs: string;
  imp_realizado: string;
  imp_motivo: string;
  imp_inicial: string;
  imp_final: string;
  ativacao_numero_parcelas: string;
  ativacao_vencimentos: string;
  ativacao_valor_parcela: string;
  id_tipo_doc_ativ: string;
  id_produto_ativ: string;
  id_cond_pag_ativ: string;
  endereco_padrao_cliente: TEnderecoPadraoCliente;
  cep: string;
  referencia: string;
  id_condominio: string;
  nf_info_adicionais: string;
  assinatura_digital: TAssinaturaDigital;
  tipo_produtos_plano: string;
  bloco: string;
  apartamento: string;
  latitude: string;
  longitude: string;
  num_parcelas_atraso: string;
  dt_ult_desiste: string;
  id_contrato_principal: string;
  gerar_finan_assin_digital_contrato: string;
  credit_card_recorrente_token: string;
  credit_card_recorrente_bandeira_cartao: string;
  id_motivo_negativacao: string;
  obs_negativacao: string;
  restricao_auto_desbloqueio: string;
  motivo_restricao_auto_desbloq: string;
  nao_susp_parc_ate: string;
  liberacao_suspensao_parcial: string;
  utilizando_auto_libera_susp_parc: string;
  restricao_auto_libera_susp_parcial: string;
  motivo_restri_auto_libera_parc: string;
  data_inicial_suspensao: string;
  data_final_suspensao: string;
  data_retomada_contrato: string;
  dt_ult_liberacao_susp_parc: string;
  base_geracao_tipo_doc: TBaseGeracaoTipoDoc;
  integracao_assinatura_digital: string;
  url_assinatura_digital: string;
  token_assinatura_digital: string;
  testemunha_assinatura_digital: string;
  document_photo: string;
  selfie_photo: string;
  [key: string]: string;
}